# Label: Documentation
Documentation:
  description: 'Changes related to documentation, guides, or markdown files.'
  color: '0075ca' # Warna biru
  changed-files:
    - any-glob-to-any-file:
        - '**/*.md'

# Label: Source
Source:
  description: 'Changes related to source code files, excluding documentation.'
  color: '7057ff' # Warna ungu
  changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/**/*.md'

# Label: Release
Release:
  description: 'Pull requests targeting the main branch for releases.'
  color: 'bfd4f2' # Warna biru muda
  base-branch: 'main'

# Label: Feature
Feature:
  description: 'Pull requests introducing new features or enhancements.'
  color: 'a2eeef' # Warna cyan
  head-branch:
    - '^feature'
    - '^feat'
    - '^enhancement'

# Label: Bug
Bug:
  description: 'Pull requests addressing bugs or hotfixes.'
  color: 'd73a4a' # Warna merah
  head-branch:
    - '^hotfix'
    - '^fix'
    - '^bugfix'

# Label: Integration
Integration:
  description: 'Pull requests related to integrations or API connections.'
  color: 'ff9f1c' # Warna oranye
  title:
    - '^integration'
    - '^integrations'

# Label: Slicing
Slicing:
  description: 'Pull requests related to UI/UX slicing or design implementation.'
  color: 'ffcc99' # Warna peach
  title: 'slicing'
